name: mobile_buyer_guide
description: Mobile Phone Buyer’s Guide Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  http_mock_adapter: ^0.3.2
  bloc_test: ^9.0.2
  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:

  uses-material-design: true
